# Generated by Django 3.0.7 on 2020-06-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(default='programador', max_length=25),
            preserve_default=False,
        ),
    ]
