# Generated by Django 3.0.7 on 2020-06-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200619_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultapet',
            name='peso_atual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultapet',
            name='motivo_consulta',
            field=models.CharField(max_length=200),
        ),
    ]
