# Generated by Django 3.0.7 on 2020-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200619_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultapet',
            name='exames_prescritos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultapet',
            name='medicamento_atual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultapet',
            name='medicamentos_prescritos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
